// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/14/2026, 3:58:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/0xscrpn/Desktop/linktree/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/plugins/**/*.{js,ts,mjs}","/Users/0xscrpn/Desktop/linktree/composables/**/*.{js,ts,mjs}","/Users/0xscrpn/Desktop/linktree/utils/**/*.{js,ts,mjs}","/Users/0xscrpn/Desktop/linktree/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/0xscrpn/Desktop/linktree/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;